// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA2A1zkK_N1rRod76BG2t7LAT4XEMFPFc',
    appId: '1:105671713030:web:cb4cf056c63f5027c27e87',
    messagingSenderId: '105671713030',
    projectId: 'ainhelios',
    authDomain: 'ainhelios.firebaseapp.com',
    databaseURL: 'https://ainhelios-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ainhelios.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpieeIKO38LSA1QT17VKsaGzlBxlVml_E',
    appId: '1:105671713030:android:a6a67f886e2fc2f9c27e87',
    messagingSenderId: '105671713030',
    projectId: 'ainhelios',
    databaseURL: 'https://ainhelios-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ainhelios.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdgM37-JZPZ05LKeI49w-F1PNzzAO3gr4',
    appId: '1:105671713030:ios:c6b2fbb399731659c27e87',
    messagingSenderId: '105671713030',
    projectId: 'ainhelios',
    databaseURL: 'https://ainhelios-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ainhelios.firebasestorage.app',
    androidClientId: '105671713030-ec7erhdficd3uv9uiph97aqt8s9ad9mn.apps.googleusercontent.com',
    iosClientId: '105671713030-nh6ddtsla8mkrrvfcmdnd46n8tf0pe31.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoinak5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdgM37-JZPZ05LKeI49w-F1PNzzAO3gr4',
    appId: '1:105671713030:ios:c6b2fbb399731659c27e87',
    messagingSenderId: '105671713030',
    projectId: 'ainhelios',
    databaseURL: 'https://ainhelios-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ainhelios.firebasestorage.app',
    androidClientId: '105671713030-ec7erhdficd3uv9uiph97aqt8s9ad9mn.apps.googleusercontent.com',
    iosClientId: '105671713030-nh6ddtsla8mkrrvfcmdnd46n8tf0pe31.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoinak5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA2A1zkK_N1rRod76BG2t7LAT4XEMFPFc',
    appId: '1:105671713030:web:0ff526f60af3552ac27e87',
    messagingSenderId: '105671713030',
    projectId: 'ainhelios',
    authDomain: 'ainhelios.firebaseapp.com',
    databaseURL: 'https://ainhelios-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ainhelios.firebasestorage.app',
  );
}
